version: 2

defaults: &defaults
  working_directory: ~/teste-circleci
  docker:
    - image: alpine:3.8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Instalar NODE e NPM
          command: apk add --update nodejs nodejs-npm

      - run:
          name: Instalar dependências
          command: npm install

      - run:
          name: Executar test
          command: npm test
